delete from reference;
delete from contact;
insert into reference values (1,1,'Charles', 'Java developer', 'Chaplin', 'friend', 1);
insert into reference values (2,2,'Montgomery', 'Top manager', 'Clift', 'brother', 3);
insert into reference values (3,3,'Harrison', 'Director', 'Ford', 'classmate', 4);
insert into reference values (4,4,'Katharine', 'Driver', 'Hepburn', 'roommate', 5);
insert into reference values (5,5,'Elizabeth', 'C++ developer', 'Taylor', 'sister', 6);
insert into reference values (6,5,'Meryl', 'Cleaner', 'Streep', 'father', 15);
insert into reference values (7,5,'Bette', 'Cleaner', 'Davis', 'friend', 2);
insert into reference values (8,6,'Cate', 'Cleaner', 'Blanchett', 'roommate', 7);
insert into reference values (9,7,'Audrey', 'Cleaner', 'Hepburn', 'brother', 11);
insert into reference values (10,8,'Kate', 'Cleaner', 'Winslet', 'roommate', 14);
insert into reference values (11,8,'Halle', 'Cleaner', 'Berry', 'sister', 18);
insert into contact values (1, 'chaplin@gmail.com', '4564521111', 'main', 1);
insert into contact values (2, 'clift@gmail.com', '7457852555', 'main', 2);
insert into contact values (3, 'ford@gmail.com', '4565522555', 'main', 3);
insert into contact values (4, 'hepburn@gmail.com', '6412587552', 'main',4);
insert into contact values (5, 'taylor@gmail.com', '7704568525', 'main', 5);
insert into contact values (6, 'streep@gmail.com', '1201254488', 'main', 6);
insert into contact values (7, 'davis@gmail.com', '7205824466', 'main', 7);
insert into contact values (8, 'blanchett@gmail.com', '5302584455', 'main', 8);
insert into contact values (9, 'hepburn@gmail.com', '5502587788', 'main', 9);
insert into contact values (10, 'winslet@gmail.com', '1102586655', 'main', 10);
insert into contact values (11, 'berry@gmail.com', '4402587788', 'main', 11);